-- CreateEnum
CREATE TYPE "DOCUMENT_ERROR_CODE" AS ENUM ('INVALID_JOB_DATA', 'DOCUMENT_NOT_FOUND', 'S3_DOWNLOAD_FAILED', 'PDF_PARSE_FAILED', 'EMBEDDING_FAILED', 'CHUNKING_FAILED', 'SOMETHING_WENT_WRONG');

-- AlterTable
ALTER TABLE "document" ADD COLUMN     "errorCode" "DOCUMENT_ERROR_CODE",
ADD COLUMN     "errorMessage" TEXT;
