version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: documently_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - documently_data:/var/lib/postgresql/data

volumes:
  documently_data:
    external: false
