[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yash-devop", email = "yashkamble.dev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.14.2",
    "sqlalchemy>=2.0.51",
    "taskipy>=1.14.1",
    "uvicorn[standard]>=0.52.0",
]

[tool.taskipy.tasks]
compose-up = "docker compose --env-file .env.local up"